import streamlit as st

from utils.artifact_loader import get_artifact_status, resolve_artifact_dir
from utils.ui_helpers import fmt_count


st.set_page_config(page_title="eCampus Learner Readiness v1.3-ext2", layout="wide")

st.title("eCampus Learner Readiness v1.3-ext2")
st.subheader("Test / Exercise Readiness Evidence Layer")

st.markdown(
    """
This branch is the artifact-based v1.3-ext2 dashboard. It reads CSV artifacts
generated by `v13_build_dashboard_base_datasets_v2.ipynb` and does not connect
to the live database or rebuild the heavy readiness logic inside Streamlit.

CAS, TAS, BLS, ALS, work habits, and readiness are evidence/proxy signals in
this version. They are not final Learn Smarter v2 predictions.
"""
)

artifact_dir = resolve_artifact_dir()
status = get_artifact_status()
loaded = status[status["exists"]]

st.caption(f"Artifact directory: `{artifact_dir}`")

cols = st.columns(4)
cols[0].metric("Artifacts loaded", fmt_count(len(loaded)))
cols[1].metric("Artifacts expected", fmt_count(len(status)))
cols[2].metric("Valid artifacts", fmt_count(status["valid"].sum()))
cols[3].metric("Missing artifacts", fmt_count((~status["exists"]).sum()))

st.subheader("Artifact Build Status")
st.dataframe(status[["artifact", "filename", "exists", "valid", "rows", "missing_required"]], use_container_width=True)

st.subheader("Navigation")
st.markdown(
    """
- `00_ext2_Home_Project_Overview`: project scope and artifact status
- `01_ext2_Definitions_Assumptions`: definitions, formulas, assumptions, caveats
- `02_ext2_Data_Quality`: data trust and diagnostic warnings
- `03_ext2_School_Subject_Summary`: School-Subject CAS Proxy
- `04_ext2_Test_Topic_Proxy_Summary`: Content/Topic TAS Proxy
- `05_ext2_Learner_Summary`: learner readiness evidence
- `06_ext2_Cohort_Context`: subscription and cohort context
- `07_ext2_Raw_Data_Explorer`: technical artifact inspection
"""
)

