import streamlit as st

from utils.artifact_loader import get_artifact_status, resolve_artifact_dir
from utils.ui_helpers import fmt_count


st.set_page_config(page_title="eCampus Learner Readiness v1.3-ext2", layout="wide")

st.title("eCampus Learner Readiness v1.3-ext2")
st.subheader("Test / Exercise Readiness Evidence Layer")

st.markdown(
    """
This is the artifact-based v1.3-ext2 dashboard. It displays CSV artifacts
generated by `v13_build_dashboard_base_datasets_v2.ipynb`.

The dashboard does not connect to the live database, does not rebuild SQL joins,
and does not recalculate core CAS/TAS/readiness logic internally.
"""
)

status = get_artifact_status()
loaded = status[status["exists"]]

st.caption(f"Artifact directory: `{resolve_artifact_dir()}`")

cols = st.columns(4)
cols[0].metric("Artifacts loaded", fmt_count(len(loaded)))
cols[1].metric("Artifacts expected", fmt_count(len(status)))
cols[2].metric("Valid artifacts", fmt_count(status["valid"].sum()))
cols[3].metric("Missing artifacts", fmt_count((~status["exists"]).sum()))

st.warning("CAS, TAS, BLS, ALS, work habits, and readiness are proxy/evidence signals in v1.3-ext2.")
st.dataframe(status[["artifact", "filename", "exists", "valid", "rows", "missing_required"]], use_container_width=True)

